/*

 TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 25

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define gameTilesBank 0
/* Start of tile array. */
extern unsigned char gameTiles[];

#define TILE_START 0
#define TILE_GOAT 44
#define TILE_EMPTY 48

/* End of TILES.H */
